### ISSUE TITLE
Demo...

### ISSUE THREAD

**Issue by LiamKenyon** [hoshsadiq/m3ufilter#2]
Looks interesting project. 

Do you have a demo?

**Comment by kalpak44** [comment]
I'm interested too :)

**Comment by LiamKenyon** [comment]
Take a look in his release, i'd not checked before opening the ticket.

**Comment by hoshsadiq** [comment]
Please look at the read me. I don't really have any demos at the moment and I don't have any public m3u lists that I can use. Maybe if I find one, then I can set up a demo.
