### ISSUE TITLE
Command not found: m3ufilter

### ISSUE THREAD

**Issue by vedran-hibler** [hoshsadiq/m3ufilter#20]
Hi!

I need some help, I have configured config.yaml file but when I run 

`m3ufilter -config /pathTo/m3ufilter-master/config.yaml`

I get terminal error 

`zsh: command not found: m3ufilter`

What do I need to run before I run m3ufilter script?

EDIT:
When I run `docker build` I get an error message: 
`COPY failed: stat /var/lib/docker/tmp/docker-builder662332369/build/m3u-filter_linux_amd64: no such file or directory`

Thank you!

**Comment by vedran-hibler** [comment]
Resolved

**Comment by hoshsadiq** [comment]
The Dockerfile assumes the application has already been built. You should instead use the prebuild docker image: `hoshsadiq/m3ufilter:latest`

**Comment by hoshsadiq** [comment]
Also, you need to download and run the m3ufilter file if you need to run.

**Comment by vedran-hibler** [comment]
Where is the m3ufilter file located? Where can I download it?

**Comment by hoshsadiq** [comment]
https://github.com/hoshsadiq/m3ufilter/releases
