### ISSUE TITLE
Filter XMLTV File

### ISSUE THREAD

**Issue by Olivier6767** [hoshsadiq/m3ufilter#25]
It would be nice if you could also filter the entries from an XMLTV file to reduce it.
Basically this would mean removing from the XMLTV file the entries linked to channels that are filtered out by the M3U filters.

The resulting XMLTV file should contain only information in line with the channels present in the .m3u file after filtering.
The filtered XMLTV file could also be served by the web integrated web server through another url (/epg.xml).

Thanks for the consideration.

**Comment by hoshsadiq** [comment]
Have been working on this for a while. If you're up for testing you can checkout the branch from #15. I haven't had time to further develop so I've not been ready to merge it just yet. That branch includes other fixes as well.

**Comment by hoshsadiq** [comment]
I've just released a new version that includes this improvement. All channels and their programmes are removed from the final EPG.
