### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by LiamKenyon** [hoshsadiq/m3ufilter#3]
`go build
can't load package: package github.com/hoshsadiq/m3ufilter: unknown import path "github.com/hoshsadiq/m3ufilter": cannot find module providing package github.com/hoshsadiq/m3ufilter`

**Comment by hoshsadiq** [comment]
Hello, you need to make sure you check out the repo in `$GOPATH/src/github.com/m3ufilter`. Ensure the following environment variables are set: `GO111MODULES=on`, `CGO_ENABLED=0`. Then you should be able to build.

I've already uploaded alpha releases if you do not want to bother with building: https://github.com/hoshsadiq/m3ufilter/releases
