### ISSUE TITLE
-playlist does not create a output file

### ISSUE THREAD

**Issue by xses22** [hoshsadiq/m3ufilter#4]
Hello I used your docker file on my server and it seems that i can't get it to output a m3u to my output folder. 

"-config /config/config.yaml -playlist /config"

My logs aren't showing any errors.

> time="2019-08-10T20:49:32+02:00" level=info msg="Scheduling cronjob to periodically update playlist."
time="2019-08-10T20:49:32+02:00" level=info msg="Parsing for the first time..."
time="2019-08-10T20:49:32+02:00" level=info msg="starting server"
time="2019-08-10T20:49:32+02:00" level=info msg="updating playlists"
time="2019-08-10T20:49:32+02:00" level=info msg="reading from provider http://xxxxxxx.com:1234/get.php?username=xxx&password=xxxx&type=m3u_plus&output=ts"
time="2019-08-10T20:49:32+02:00" level=info msg="Parsing 1000 streams"
time="2019-08-10T20:49:33+02:00" level=info msg="Parsing 2000 streams"
time="2019-08-10T20:49:33+02:00" level=info msg="Parsing 3000 streams"
time="2019-08-10T20:49:33+02:00" level=info msg="Parsing 4000 streams"
time="2019-08-10T20:49:33+02:00" level=info msg="Parsing 5000 streams"
time="2019-08-10T20:49:33+02:00" level=info msg="Parsing 6000 streams"
time="2019-08-10T20:49:33+02:00" level=info msg="Found 763 valid streams"
time="2019-08-10T20:49:33+02:00" level=info msg=done

**Comment by hoshsadiq** [comment]
What does your core config look like?

**Comment by knaksbrig** [comment]
Hi. I'm having the same issue where the -log or -playlist arguments don't seem to be working in either Docker (prefered) or native linux. I'm getting 'no such file or directory' if the file doesn't exist; and if I create the file manually, I then get 'log.txt: bad file descriptor' or 'playlist.m3u: bad file descriptor'. Any ideas?

**Comment by hoshsadiq** [comment]
Can you tell me what commands you are running?

**Comment by knaksbrig** [comment]
Followed the README and running 'm3ufilter -config /path/to/config.yaml' works with a basic config. I can see the parsed output via stdout and also if I run as a server (GET /playlist.m3u). But, if I try to run once with the -playlist argument, I get the above errors.

**Comment by hoshsadiq** [comment]
I can't do anything with what you've given me, please paste the exact commands you're running with their output. E.g.:

```bash
$ docker run bla
something happened
```

In addition also post the `config.yaml` file taking care to remove the URLs to your providers if they are sensitive URLs.

**Comment by Olivier6767** [comment]
I would like o reopen this issue as I have the same problem.

**Platform:** Ubuntu 18.04.4 LTS - AMD64
**Version:** v0.1-beta.3 - **using binary:** m3u-filter_linux_arm64 - Downloaded executable, did NOT build from source myself

**Command line:** `./m3u-filter -config ./data/m3u.conf -playlist ./data/playlist.m3u`

**Error Message:** 
`panic: open ./data/playlist.m3u: no such file or directory`

`goroutine 1 [running]:
main.fd(0x7ffeacbae7c5, 0x13, 0x7ffeacbae700, 0xf)
        /home/travis/gopath/src/github.com/hoshsadiq/m3ufilter/cmd/m3u-filter/main.go:59 +0xf6
main.main()
        /home/travis/gopath/src/github.com/hoshsadiq/m3ufilter/cmd/m3u-filter/main.go:30 +0x228`

The error is the same if I specify a logfile, with or without the **-playlist** argument.

I tried creating an empty **playlist.m3u** file but then I get: 
`FATA[2020-04-01T20:19:31+02:00]writer/m3u.go:15 writer.writeM3U() unable to write extm3u, err = !!write ./data/playlist.m3u: bad file descriptor`

**Content of m3u.conf file:**
`core:`
`  output: m3u`
`  group_order:`
`    - France`
`    - Switzerland`
`    - Belgium`
`    - VOD France`
`providers:`
`  - uri: file:///home/Services/m3u-filter/data/playlist.ts`
`    filters:`
`      - match(Group, "France")`
`      - match(Group, "Switzerland")`
`      - match(Group, "Belgium")`
`      - match(Group, "VOD France")`

If I don't specify the **-log** or **-playlist** arguments the filtered m3u list is displayed on the console properly.

Hopefully this will help narrowing down the issue.
